import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Vessa Hospital",
  description: "Generated by Vessa Hospital",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ro">
      <head>
        {/* Google Analytics Tag */}
        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXXXX"
        ></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
                      window.dataLayer = window.dataLayer || [];
                      function gtag(){dataLayer.push(arguments);}
                      gtag('js', new Date());
                      gtag('config', 'G-Q1PS9ZXCXD');
                  `,
          }}
        />
      </head>
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
